baseURL: https://morethancode.be
languageCode: en
title: More Than Code
author: Ken Bonny
markup:
    defaultMarkdownHandler: blackfriday
languages:
    en:
        languageName: English
        params:
            description: I am Ken Bonny, a software craftsman who specialises in Microsoft technology.
            vat: VAT
    nl:
        languageName: Nederlands
        params:
            description: Ik ben Ken Bonny, een software vakman die zich specialiseert in Microsoft technologie.
            vat: BTW
